name: Docker Security Scan

on:
  push:
    branches: 
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Build php-dev image
    #   id: build_php_dev
    #   run: docker build -f php/debian/dev/Dockerfile -t srijanlabs/php-dev:latest php/debian/dev
    # - name: Scan php-dev image
    #   id: scan_php_dev
    #   uses: anchore/scan-action@master
    #   with:
    #     image-reference: "srijanlabs/php-dev:latest"
    #     dockerfile-path: "php/debian/dev/Dockerfile"
    #     fail-build: false
        # acs-report-enable: true
    - name: Rename file
      run: mv ./anchore-reports/vulnerabilities.json ./anchore-reports/scan_php-dev.json
    - name: Raise issue
      id: raise_issue_php_dev
#       if: contains(steps.scan_php_dev.outputs.policycheck, 'pass')
      uses: WSMathias/create-an-issue@v2.1.11
      # with:
      #   reports-path-pattern: ./anchore-reports/vulnerabilities-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IMAGE: srijanlabs/php-dev:latest
