name: Docker Security Scan

on:
  # Run every midnight.
  schedule:
    - cron: '22 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: testing 
    # debian
    - name: Build debian image
      run: docker build -f base/debian/Dockerfile -t srijanlabs/debian:latest base/debian
    - name: Scan debian image
      uses: anchore/scan-action@master
      with:
        image-reference: "srijanlabs/debian:latest"
        dockerfile-path: "base/debian/Dockerfile"
        fail-build: true
    # apache
    - name: Build apache image
      run: docker build -f apache/debian/Dockerfile -t srijanlabs/apache:latest apache/debian
    - name: Scan apache image
      uses: anchore/scan-action@master
      with:
        image-reference: "srijanlabs/apache:latest"
        dockerfile-path: "apache/debian/Dockerfile"
        fail-build: true
    # php-base
    - name: Build php image
      run: docker build -f php/debian/base/Dockerfile -t srijanlabs/php:latest php/debian/base
    - name: Scan php image
      uses: anchore/scan-action@master
      with:
        image-reference: "srijanlabs/php:latest"
        dockerfile-path: "php/debian/base/Dockerfile"
        fail-build: true
    # php-cli
    - name: Build php-cli image
      run: docker build -f php/debian/cli/Dockerfile -t srijanlabs/php-cli:latest php/debian/cli
    - name: Scan php-cli image
      uses: anchore/scan-action@master
      with:
        image-reference: "srijanlabs/php-cli:latest"
        dockerfile-path: "php/debian/cli/Dockerfile"
        fail-build: true
    # php-dev
    - name: Build php-dev image
      run: docker build -f php/debian/dev/Dockerfile -t srijanlabs/php-dev:latest php/debian/dev
    - name: Scan php-cli image
      uses: anchore/scan-action@master
      with:
        image-reference: "srijanlabs/php-dev:latest"
        dockerfile-path: "php/debian/dev/Dockerfile"
        fail-build: true
    # php-fpm
    - name: Build php-fpm image
      run: docker build -f php/debian/fpm/Dockerfile -t srijanlabs/php-fpm:latest php/debian/fpm
    - name: Scan php-fpm image
      uses: anchore/scan-action@master
      with:
        image-reference: "srijanlabs/php-fpm:latest"
        dockerfile-path: "php/debian/fpm/Dockerfile"
        fail-build: true
    # php-fpm
    - name: Build php-fpm-apache image
      run: docker build -f php-fpm-apache/debian/Dockerfile -t srijanlabs/php-fpm:latest php-fpm-apache/debian
    - name: Scan php-fpm image
      uses: anchore/scan-action@master
      with:
        image-reference: "srijanlabs/php-fpm:latest"
        dockerfile-path: "php/debian/fpm/Dockerfile"
        fail-build: true
